---

- name: Gather Raspberry Pi telemetry
  hosts: all
  gather_facts: true
  become: true
  gather_subset: hardware

  tasks:
    - name: Get on-board temperature
      shell: vcgencmd measure_temp | grep --only-matching --extended-regexp "[0-9]{2}"
      register: temp

    - name: Save temperature to facts
      set_fact:
        core_temperature: "{{ temp.stdout_lines }}"
        cacheable: yes

    - name: Get uptime
      shell: uptime --since | awk '{ printf $1 }'
      register: uptime_since

    - name: Save uptime to facts
      set_fact:
        boot_date: "{{ uptime_since.stdout_lines }}"
        cacheable: yes

    - name: Get cpu average
      shell: uptime | awk '{print $NF}'
      register: cpu_avg

    - name: Save CPU average
      set_fact:
        cpu_average: "{{ cpu_avg.stdout_lines }}"
        cacheable: yes

    - name: Get disk utilization
      shell: df --human-readable --output=pcent . | tail -1 | grep --only-matching --extended-regexp "[0-9]+"
      register: disk_util

    - name: Save disk utilization
      set_fact:
        disk_utilization: "{{ disk_util.stdout_lines }}"
        cacheable: yes


